"""initial schema

Revision ID: 96245ead2bd0
Revises: 
Create Date: 2026-09-20 19:52:55.077810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Custom TypeDecorators (GUID, JSONBType) are referenced by name below.
# Alembic's autogenerate emits the dotted path but not the import.
import shipdoc.adapters.db.models


# revision identifiers, used by Alembic.
revision: str = '96245ead2bd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('email_id', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), server_default='corpus', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('corpus','upload')", name=op.f('ck_emails_source_vocab')),
    sa.PrimaryKeyConstraint('email_id', name=op.f('pk_emails'))
    )
    op.create_table('label_proposals',
    sa.Column('proposal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('label_raw', sa.Text(), nullable=False),
    sa.Column('label_normalised', sa.Text(), nullable=False),
    sa.Column('proposed_field', sa.Text(), nullable=True),
    sa.Column('proposed_by', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('evidence_doc', sa.Text(), nullable=False),
    sa.Column('evidence_line', sa.Integer(), nullable=True),
    sa.Column('evidence_context', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('decided_by', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("status in ('pending','approved','rejected')", name=op.f('ck_label_proposals_status_vocab')),
    sa.PrimaryKeyConstraint('proposal_id', name=op.f('pk_label_proposals'))
    )
    op.create_index('ix_label_proposals_status', 'label_proposals', ['status'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', shipdoc.adapters.db.models.GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('code_version', sa.Text(), nullable=False),
    sa.Column('config_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('learned_labels_sha256', sa.CHAR(length=64), server_default='', nullable=False),
    sa.Column('decisions_sha256', sa.CHAR(length=64), server_default='', nullable=False),
    sa.Column('llm_provider', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('degraded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('submission_sha256', sa.CHAR(length=64), nullable=True),
    sa.Column('run_summary_sha256', sa.CHAR(length=64), nullable=True),
    sa.CheckConstraint("status in ('running','complete','failed')", name=op.f('ck_runs_status_vocab')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_runs'))
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('blob_url', sa.Text(), nullable=True),
    sa.Column('detected_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.email_id'], name=op.f('fk_attachments_email_id_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('email_id', 'filename', name='uq_attachment_email_filename')
    )
    op.create_table('evaluations',
    sa.Column('run_id', shipdoc.adapters.db.models.GUID(), nullable=False),
    sa.Column('macro_f1', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('defect_f1', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('end_to_end', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('reliability_p', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('reliability_r', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_evaluations_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_evaluations'))
    )
    op.create_table('learned_labels',
    sa.Column('label_normalised', sa.Text(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field', sa.Text(), nullable=False),
    sa.Column('proposal_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['label_proposals.proposal_id'], name=op.f('fk_learned_labels_proposal_id_label_proposals')),
    sa.PrimaryKeyConstraint('label_normalised', 'approved_at', name=op.f('pk_learned_labels'))
    )
    op.create_index('uq_learned_labels_active', 'learned_labels', ['label_normalised'], unique=True, postgresql_where=sa.text('active'), sqlite_where=sa.text('active'))
    op.create_table('llm_calls',
    sa.Column('call_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', shipdoc.adapters.db.models.GUID(), nullable=False),
    sa.Column('email_id', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('prompt_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('response_raw', sa.Text(), nullable=True),
    sa.Column('response_valid', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("purpose in ('classify','label_propose')", name=op.f('ck_llm_calls_purpose_vocab')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_llm_calls_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_id', name=op.f('pk_llm_calls'))
    )
    op.create_index('ix_llm_calls_run_purpose', 'llm_calls', ['run_id', 'purpose'], unique=False)
    op.create_table('records',
    sa.Column('record_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', shipdoc.adapters.db.models.GUID(), nullable=False),
    sa.Column('email_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('reason_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('has_defect', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('awaiting_documents', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("decided_by is null or decided_by in ('rule','llm')", name=op.f('ck_records_decided_by_vocab')),
    sa.CheckConstraint("state in ('resolved','escalated','failed')", name=op.f('ck_records_state_vocab')),
    sa.CheckConstraint("status in ('OK','MISMATCH','NEEDS_REVIEW')", name=op.f('ck_records_status_vocab')),
    sa.ForeignKeyConstraint(['email_id'], ['emails.email_id'], name=op.f('fk_records_email_id_emails')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_records_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_records')),
    sa.UniqueConstraint('run_id', 'email_id', name='uq_records_run_email')
    )
    op.create_index('ix_records_email', 'records', ['email_id'], unique=False)
    op.create_index('ix_records_run_category', 'records', ['run_id', 'category'], unique=False)
    op.create_index('ix_records_run_status', 'records', ['run_id', 'status'], unique=False)
    op.create_table('review_decisions',
    sa.Column('decision_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Text(), nullable=False),
    sa.Column('field', sa.Text(), nullable=True),
    sa.Column('decision_type', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('corrected_category', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("decision_type in ('confirm','correct_value','override_category','clear_escalation','retry')", name=op.f('ck_review_decisions_decision_type_vocab')),
    sa.ForeignKeyConstraint(['email_id'], ['emails.email_id'], name=op.f('fk_review_decisions_email_id_emails')),
    sa.ForeignKeyConstraint(['superseded_by'], ['review_decisions.decision_id'], name=op.f('fk_review_decisions_superseded_by_review_decisions')),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_review_decisions'))
    )
    op.create_index('ix_review_decisions_email_active', 'review_decisions', ['email_id'], unique=False, postgresql_where=sa.text('superseded_by IS NULL'), sqlite_where=sa.text('superseded_by IS NULL'))
    op.create_table('submissions',
    sa.Column('run_id', shipdoc.adapters.db.models.GUID(), nullable=False),
    sa.Column('payload', shipdoc.adapters.db.models.JSONBType(), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_submissions_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_submissions'))
    )
    op.create_table('comparisons',
    sa.Column('comparison_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('field', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('leaning', sa.Text(), nullable=True),
    sa.Column('si_value', sa.Text(), nullable=True),
    sa.Column('bl_value', sa.Text(), nullable=True),
    sa.Column('si_numeric', sa.Numeric(), nullable=True),
    sa.Column('bl_numeric', sa.Numeric(), nullable=True),
    sa.Column('si_evidence', shipdoc.adapters.db.models.JSONBType(), nullable=True),
    sa.Column('bl_evidence', shipdoc.adapters.db.models.JSONBType(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.CheckConstraint("verdict in ('MATCH','MISMATCH','CANNOT_DETERMINE')", name=op.f('ck_comparisons_verdict_vocab')),
    sa.ForeignKeyConstraint(['record_id'], ['records.record_id'], name=op.f('fk_comparisons_record_id_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comparison_id', name=op.f('pk_comparisons')),
    sa.UniqueConstraint('record_id', 'field', name='uq_comparisons_record_field')
    )
    op.create_index('ix_comparisons_record', 'comparisons', ['record_id'], unique=False)
    op.create_table('stage_events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.record_id'], name=op.f('fk_stage_events_record_id_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_stage_events')),
    sa.UniqueConstraint('record_id', 'seq', name='uq_stage_events_record_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_events')
    op.drop_index('ix_comparisons_record', table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_table('submissions')
    op.drop_index('ix_review_decisions_email_active', table_name='review_decisions', postgresql_where=sa.text('superseded_by IS NULL'), sqlite_where=sa.text('superseded_by IS NULL'))
    op.drop_table('review_decisions')
    op.drop_index('ix_records_run_status', table_name='records')
    op.drop_index('ix_records_run_category', table_name='records')
    op.drop_index('ix_records_email', table_name='records')
    op.drop_table('records')
    op.drop_index('ix_llm_calls_run_purpose', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('uq_learned_labels_active', table_name='learned_labels', postgresql_where=sa.text('active'), sqlite_where=sa.text('active'))
    op.drop_table('learned_labels')
    op.drop_table('evaluations')
    op.drop_table('attachments')
    op.drop_table('runs')
    op.drop_index('ix_label_proposals_status', table_name='label_proposals')
    op.drop_table('label_proposals')
    op.drop_table('emails')
    # ### end Alembic commands ###
